2021-03-01 04:07:43,932 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 8301, 'cityId': 1, 'name': '大地影院（通州米拉家园店）', 'addr': '通州区马驹桥新海东路1号（豪润生活广场7层）', 'lat': 39.760006, 'lng': 116.54555, 'poiId': 6151046, 'shopId': 16790750}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,934 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 14381, 'cityId': 1, 'name': '博纳国际影城（通州土桥店）', 'addr': '通州区八通线土桥地铁站向东900米华远好天地购物中心3层（迪卡侬通州店）', 'lat': 39.87101, 'lng': 116.698235, 'poiId': 51455681, 'shopId': 24902472}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,935 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 16680, 'cityId': 1, 'name': '华夏天合国际影城', 'addr': '通州区台湖镇定海园二里15号楼新城商厦4层', 'lat': 39.799076, 'lng': 116.56582, 'poiId': 131682620, 'shopId': 76847724}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,937 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 2379, 'cityId': 1, 'name': '平谷区影剧院', 'addr': '平谷区府前街3号', 'lat': 40.14054, 'lng': 117.122406, 'poiId': 1156598, 'shopId': 1767715}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,939 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 14634, 'cityId': 1, 'name': '耀莱成龙影城（临河里店）', 'addr': '通州区临河里33号楼华业玫瑰商业中心D2号楼三层', 'lat': 39.881195, 'lng': 116.682556, 'poiId': 92950934, 'shopId': 57462444}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,940 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 27915, 'cityId': 1, 'name': '新影联长天影城（次渠免费停车店）', 'addr': '通州区台湖镇东石东四路万科城市之光2号院11号楼-2层01号', 'lat': 39.81842, 'lng': 116.58723, 'poiId': 833855140, 'shopId': 833855140}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,941 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 8654, 'cityId': 1, 'name': '米瑞酷影城（乔庄店）', 'addr': '通州区运河西大街乔庄卜蜂莲花超市一层（近吉野家）', 'lat': 39.891575, 'lng': 116.68774, 'poiId': 4800806, 'shopId': 17215553}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,942 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 26075, 'cityId': 1, 'name': '米瑞酷国际影城（平谷店）', 'addr': '平谷区平谷大街电视塔环岛东北角', 'lat': 40.159416, 'lng': 117.12401, 'poiId': 188832315, 'shopId': 126147066}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,943 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 15082, 'cityId': 1, 'name': '华联影城（平谷店）', 'addr': '平谷区迎宾路1号院22号楼五层F5-13', 'lat': 40.146297, 'lng': 117.094284, 'poiId': 97314976, 'shopId': 58217510}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,945 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 10964, 'cityId': 1, 'name': '万达影城（银兴光魔店）', 'addr': '通州区翠景北里21号领展购物广场·京通5F', 'lat': 39.889038, 'lng': 116.6586, 'poiId': 6139543, 'shopId': 19450958}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,946 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 16152, 'cityId': 1, 'name': 'CGV影城（亦庄店）', 'addr': '大兴区经济技术开发区荣京东街大族广场S3三层', 'lat': 39.79078, 'lng': 116.51304, 'poiId': 105355906, 'shopId': 68937200}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,947 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 26095, 'cityId': 1, 'name': '华联影城（通州店）', 'addr': '通州区通胡大街甲3号3层03层商业3楼', 'lat': 39.918552, 'lng': 116.700325, 'poiId': 188992887, 'shopId': 126300192}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,948 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 15421, 'cityId': 1, 'name': '北京东融国际影城（月亮河店）', 'addr': '通州区永顺镇芙蓉园513号楼', 'lat': 39.919575, 'lng': 116.67752, 'poiId': 99968119, 'shopId': 58964841}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,949 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 36470, 'cityId': 1, 'name': '纳美国际影城（通州店）', 'addr': '通州区六合桥西甲一号（免费停车）', 'lat': 39.937984, 'lng': 116.703514, 'poiId': 1610952702, 'shopId': 1610952702}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,950 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 11132, 'cityId': 1, 'name': '唐阁影城（亦庄力宝华联店）', 'addr': '大兴区经济技术开发区荣华中路8号院华联力宝购物中心四层', 'lat': 39.805687, 'lng': 116.50168, 'poiId': 5165994, 'shopId': 18583064}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,952 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 26314, 'cityId': 1, 'name': 'CGV影城（天宫院凯德4DX店）', 'addr': '大兴区华佗路与新源大街交叉口凯德MALL6F', 'lat': 39.67226, 'lng': 116.31903, 'poiId': 189992899, 'shopId': 127232621}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,953 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 34, 'cityId': 1, 'name': '大料国际影城（创意生活广场店）', 'addr': '大兴区亦庄经济开发区文化园东路6号创意生活广场三层', 'lat': 39.810562, 'lng': 116.50354, 'poiId': 82601, 'shopId': 66749924}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,954 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 10837, 'cityId': 1, 'name': '万达影城（通州万达店）', 'addr': '通州区新华西街58号万达广场1号楼5层（厨艺宾馆对面）', 'lat': 39.905933, 'lng': 116.642715, 'poiId': 41521114, 'shopId': 21319178}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,955 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 2, 'cityId': 1, 'name': '博纳国际影城（通州北苑店）', 'addr': '通州区杨庄北里52号华联天时名苑购物中心4楼（近通州北苑地铁站）', 'lat': 39.903866, 'lng': 116.63641, 'poiId': 363447, 'shopId': 4283694}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,956 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 27677, 'cityId': 1, 'name': '星典巨幕影城（生物医药地铁站）', 'addr': '大兴区永大路东盛明发广场北门5层', 'lat': 39.687813, 'lng': 116.32699, 'poiId': 1224012111, 'shopId': 1224012111}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,957 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 15915, 'cityId': 1, 'name': 'SFC上影影城（北京大兴龙湖IMAX店）', 'addr': '大兴区永兴路7号院1号楼3F-Z2', 'lat': 39.686363, 'lng': 116.32075, 'poiId': 96251713, 'shopId': 67352197}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,958 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 15415, 'cityId': 1, 'name': '北京东融国际影城（西直河店）', 'addr': '朝阳区西直河商业广场华联购物广场1楼', 'lat': 39.843647, 'lng': 116.527336, 'poiId': 91811925, 'shopId': 56955107}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,959 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 15773, 'cityId': 1, 'name': '卢米埃影城（住总万科店）', 'addr': '大兴区忠凉路万科广场5层（地铁旧宫站）', 'lat': 39.80576, 'lng': 116.460175, 'poiId': 93511270, 'shopId': 66240062}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,960 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 36628, 'cityId': 1, 'name': '金逸影城（大兴大悦春风里店）', 'addr': '大兴区黄村镇黄村东大街38号院大兴大悦春风里5F-19', 'lat': 39.730297, 'lng': 116.342415, 'poiId': 910733650, 'shopId': 910733650}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,962 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 2598, 'cityId': 1, 'name': '华美国际影城', 'addr': '大兴区旧宫小红门路39号', 'lat': 39.814774, 'lng': 116.45463, 'poiId': 6685358, 'shopId': 6227626}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,963 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 2243, 'cityId': 1, 'name': '完美世界影城（北京管庄店）', 'addr': '朝阳区朝阳路京通苑30号楼L307PLus365购物中心三层', 'lat': 39.912422, 'lng': 116.59609, 'poiId': 1677952, 'shopId': 5465688}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,964 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 179, 'cityId': 1, 'name': '大兴影剧院', 'addr': '大兴区黄村西大街15号', 'lat': 39.7323, 'lng': 116.33801, 'poiId': 324698, 'shopId': 1767607}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,965 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 10954, 'cityId': 1, 'name': '大地影院（垡头永辉店）', 'addr': '朝阳区南杨庄路与武基街交叉口西南方向50米路南（垡头永辉超市，翠城馨园401号楼地下一层）', 'lat': 39.856853, 'lng': 116.50524, 'poiId': 41877507, 'shopId': 18973569}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,966 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 13204, 'cityId': 1, 'name': '卢米埃影城（长楹天街IMAX店）', 'addr': '朝阳区朝阳北路长楹天街购物中心东区5F-09', 'lat': 39.92509, 'lng': 116.60262, 'poiId': 52539636, 'shopId': 19495446}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,967 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 129, 'cityId': 1, 'name': '保利国际影城（万源店）', 'addr': '丰台区东高地万源西里航天万源广场5层', 'lat': 39.80268, 'lng': 116.4236, 'poiId': 299479, 'shopId': 2937601}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,969 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 1692, 'cityId': 1, 'name': '金逸影城（双桥店）', 'addr': '朝阳区双桥路3号东星时尚广场5层（近永辉超市）', 'lat': 39.90865, 'lng': 116.575806, 'poiId': 1439570, 'shopId': 6266998}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,970 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 15018, 'cityId': 1, 'name': '最影城', 'addr': '大兴区兴华大街百联清城购物中心3层北侧', 'lat': 39.738937, 'lng': 116.33174, 'poiId': 95968537, 'shopId': 48033351}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,971 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 8065, 'cityId': 1, 'name': '沃美影城（常营店）', 'addr': '朝阳区朝阳北路17号华联购物中心西区4层', 'lat': 39.926247, 'lng': 116.59568, 'poiId': 5529977, 'shopId': 13881483}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,972 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 26520, 'cityId': 1, 'name': '京南电影院', 'addr': '大兴区丽园路9号3层303', 'lat': 39.750244, 'lng': 116.331726, 'poiId': 191115805, 'shopId': 128292063}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,973 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 25290, 'cityId': 1, 'name': '自由人影城（爱琴海店）', 'addr': '大兴区旧宫镇久敬庄路大兴爱琴海购物公园T2区5层', 'lat': 39.81873, 'lng': 116.421776, 'poiId': 170879964, 'shopId': 103882684}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,974 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 10951, 'cityId': 1, 'name': '大地影院（十里河铭泽店）', 'addr': '朝阳区西大望南路与弘燕南一路交叉口铭泽生活广场5层', 'lat': 39.864407, 'lng': 116.47688, 'poiId': 40086376, 'shopId': 21363204}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,975 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 2392, 'cityId': 1, 'name': '保利国际影城（绿地缤纷城店）', 'addr': '大兴区金星西路3号绿地缤纷城东岸4层', 'lat': 39.76452, 'lng': 116.33412, 'poiId': 1481117, 'shopId': 4523269}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,976 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 262, 'cityId': 1, 'name': '东都影城', 'addr': '朝阳区东四环中路195号华腾新天地五层（近迪卡侬）', 'lat': 39.88505, 'lng': 116.48847, 'poiId': 30903, 'shopId': 2241361}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,977 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 36665, 'cityId': 1, 'name': '国文影城（正华店）', 'addr': '丰台区东铁匠营政馨园三区正华商城地下1层', 'lat': 39.845512, 'lng': 116.43176, 'poiId': 528570323, 'shopId': 528570323}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,978 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 16832, 'cityId': 1, 'name': '中影华臣影城（石榴中心店）', 'addr': '丰台区榴乡路88号院石榴中心斯坦福广场B1层', 'lat': 39.841423, 'lng': 116.42238, 'poiId': 150259374, 'shopId': 77234913}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,979 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 36076, 'cityId': 1, 'name': '博纳国际影城（大郊亭IMAX旗舰店）', 'addr': '朝阳区东四环中路芳圆里ID MALL 5层', 'lat': 39.88877, 'lng': 116.48806, 'poiId': 556199961, 'shopId': 556199961}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,980 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 17280, 'cityId': 1, 'name': '京港影城万达院线加盟店', 'addr': '丰台区光彩路京港城生活广场6楼（京深海鲜市场对面）', 'lat': 39.8405, 'lng': 116.4146, 'poiId': 156648558, 'shopId': 83503582}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,982 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 11082, 'cityId': 1, 'name': '耀莱成龙影城（西红门店）', 'addr': '大兴区欣旺北大街8号鸿坤广场6层（地铁4号线西红门站Ｂ口向东４００米路北）', 'lat': 39.79156, 'lng': 116.339836, 'poiId': 41278576, 'shopId': 21648087}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,983 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 16657, 'cityId': 1, 'name': '万达影城（槐房店）', 'addr': '丰台区槐房南路6号院万达广场4层', 'lat': 39.81357, 'lng': 116.368164, 'poiId': 131412291, 'shopId': 76759201}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,984 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 24573, 'cityId': 1, 'name': '寰映影城（合生汇店）', 'addr': '朝阳区西大望路甲22号院1号楼商业部分5层11/12号', 'lat': 39.893967, 'lng': 116.47848, 'poiId': 164888633, 'shopId': 97984099}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,985 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 10987, 'cityId': 1, 'name': '金逸影城（荟聚IMAX店）', 'addr': '大兴区欣宁街15号荟聚购物中心H区3层', 'lat': 39.786392, 'lng': 116.32718, 'poiId': 40697227, 'shopId': 21088644}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,986 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 35937, 'cityId': 1, 'name': '光耀华纳影城（免费停车大红门店）', 'addr': '丰台区北京市  集美家居大红门店南大门6号馆东南门上电影院', 'lat': 39.832726, 'lng': 116.389946, 'poiId': 1287722848, 'shopId': 1287722848}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,987 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 26958, 'cityId': 1, 'name': '观华全色彩激光影城（盒马鲜生店）', 'addr': '朝阳区十里堡新城市广场负一层观华国际影城', 'lat': 39.91526, 'lng': 116.50541, 'poiId': 191800575, 'shopId': 128960821}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,988 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 88, 'cityId': 1, 'name': '金逸影城（朝阳大悦城IMAX店）', 'addr': '朝阳区朝阳北路101号朝阳大悦城商场8层', 'lat': 39.924355, 'lng': 116.51871, 'poiId': 1548100, 'shopId': 3899104}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,989 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 236, 'cityId': 1, 'name': '劲松电影院', 'addr': '朝阳区劲松中街404号', 'lat': 39.88321, 'lng': 116.45597, 'poiId': 82588, 'shopId': 1767685}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,990 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 43, 'cityId': 1, 'name': '博纳国际影城（方庄店）', 'addr': '丰台区蒲黄榆路28号（地铁5号线、14号线C出口）', 'lat': 39.863983, 'lng': 116.42227, 'poiId': 82556, 'shopId': 4283316}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,991 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 14430, 'cityId': 1, 'name': '保利国际影城（东坝店）', 'addr': '朝阳区东坝中路38号金隅嘉品MALL5层', 'lat': 39.951622, 'lng': 116.54773, 'poiId': 73452594, 'shopId': 36835708}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,992 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 26867, 'cityId': 1, 'name': '苏宁影城（慈云寺店）', 'addr': '朝阳区慈云寺北里118号楼负一层', 'lat': 39.916183, 'lng': 116.49416, 'poiId': 191486037, 'shopId': 128668918}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,993 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 36327, 'cityId': 1, 'name': '中影乐成影城（双井乐成中心店）', 'addr': '朝阳区东三环中路乐成中心SPACE3商场二层', 'lat': 39.89444, 'lng': 116.4622, 'poiId': 811306240, 'shopId': 811306240}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,994 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 9730, 'cityId': 1, 'name': '耀莱成龙影城（慈云寺店）', 'addr': '朝阳区北京市慈云寺北里209号远洋未来汇3层', 'lat': 39.916153, 'lng': 116.492424, 'poiId': 4230363, 'shopId': 15963005}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,995 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 135, 'cityId': 1, 'name': 'UME影城（双井CGS 激光巨幕店）', 'addr': '朝阳区东三环中路65号富力广场北区5层', 'lat': 39.89549, 'lng': 116.46073, 'poiId': 291070, 'shopId': 2648068}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,996 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 2548, 'cityId': 1, 'name': '华谊兄弟影院（IMAX洋桥店）', 'addr': '丰台区马家堡东路101号院10号银泰百货6层地铁10号线角门东站D口', 'lat': 39.844296, 'lng': 116.38567, 'poiId': 1547150, 'shopId': 4514763}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,997 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 5987, 'cityId': 1, 'name': '嘉华国际影城（4K激光巨幕 活力东方店）', 'addr': '朝阳区姚家园路甲1号活力东方奥特莱斯购物中心4楼（姚家园）', 'lat': 39.940395, 'lng': 116.52247, 'poiId': 2578227, 'shopId': 8068247}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,998 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 25866, 'cityId': 1, 'name': '华联影院（公益西桥店）', 'addr': '丰台区城南嘉园益城园14号楼F3-40', 'lat': 39.83433, 'lng': 116.369705, 'poiId': 185252000, 'shopId': 122716815}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:43,999 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 27451, 'cityId': 1, 'name': '魔影国际影城（达美B3停车场免费停车店）', 'addr': '朝阳区青年路7号院100幢-1层', 'lat': 39.937157, 'lng': 116.51653, 'poiId': 195606770, 'shopId': 132617626}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,000 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 15070, 'cityId': 1, 'name': '大地影院（大红门合生广场店）', 'addr': '丰台区果园8号楼合生广场6层地铁八号线木樨园站C口（西南口）出直行过桥，右转合生广场六层，3号，7号直梯可直达', 'lat': 39.85595, 'lng': 116.397896, 'poiId': 78978010, 'shopId': 33577938}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,001 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 264, 'cityId': 1, 'name': '万达影城（CBD店）', 'addr': '朝阳区建国路93号万达广场B座3层', 'lat': 39.909027, 'lng': 116.4709, 'poiId': 30863, 'shopId': 2034184}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,002 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 25386, 'cityId': 1, 'name': '乐开花影院', 'addr': '朝阳区东坝李家坟7号创意总社1949传媒产业基地6号楼', 'lat': 39.95602, 'lng': 116.52545, 'poiId': 177550607, 'shopId': 110378880}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,003 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 23, 'cityId': 1, 'name': '百丽宫影城（国贸店）', 'addr': '朝阳区建国门外大街1号国贸商城北区B1层B120', 'lat': 39.912525, 'lng': 116.45976, 'poiId': 3281398, 'shopId': 4510330}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,004 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 25417, 'cityId': 1, 'name': '新影联东申影城（贵友店）', 'addr': '朝阳区建国门外大街甲5号贵友大厦4层', 'lat': 39.909073, 'lng': 116.4511, 'poiId': 165629018, 'shopId': 98656628}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,005 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 25274, 'cityId': 1, 'name': '英皇电影城（英皇集团中心店）', 'addr': '朝阳区建外大街丁12号英皇集团中心B1层', 'lat': 39.90758, 'lng': 116.444916, 'poiId': 170577418, 'shopId': 103578350}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,006 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 42, 'cityId': 1, 'name': '保利国际影城（凯德MALL·大峡谷店）', 'addr': '丰台区南三环西路16号凯德大峡谷购物中心5楼', 'lat': 39.85452, 'lng': 116.36676, 'poiId': 339944, 'shopId': 3875275}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,007 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 249, 'cityId': 1, 'name': '朝阳剧场', 'addr': '朝阳区东三环北路36号呼家楼北（近朝阳北路）', 'lat': 39.922314, 'lng': 116.462105, 'poiId': 82595, 'shopId': 2105842}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,009 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 16773, 'cityId': 1, 'name': '中影星美国际影城（耳东）世贸天阶店', 'addr': '朝阳区光华路9号世贸天阶商业南街B1层', 'lat': 39.916237, 'lng': 116.45202, 'poiId': 150027704, 'shopId': 76949371}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,010 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 27551, 'cityId': 1, 'name': '沃美启泰影城（世界城店）', 'addr': '朝阳区金汇路101幢中骏世界城E座B1层（世贸天阶商业街北侧）', 'lat': 39.91773, 'lng': 116.45229, 'poiId': 1898188655, 'shopId': 1898188655}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,011 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 24263, 'cityId': 1, 'name': '耀莱成龙影城（花乡店）', 'addr': '丰台区南四环西路76号北京花乡奥莱村第十三号楼三层四层', 'lat': 39.82602, 'lng': 116.3231, 'poiId': 163970546, 'shopId': 97118119}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,012 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 270, 'cityId': 1, 'name': '搜秀影城', 'addr': '东城区崇外大街40号搜秀城9层', 'lat': 39.896397, 'lng': 116.419266, 'poiId': 82579, 'shopId': 1879417}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,013 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 119, 'cityId': 1, 'name': '百老汇影城（国瑞购物中心店）', 'addr': '东城区崇文门外大街18号国瑞城购物中心首层/-2层', 'lat': 39.897575, 'lng': 116.420135, 'poiId': 1048975, 'shopId': 3053914}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,014 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 5736, 'cityId': 1, 'name': '卢米埃影城（芳草地店）', 'addr': '朝阳区东大桥路9号侨福芳草地购物中心LG2-26（尚都SOHO对面）', 'lat': 39.91955, 'lng': 116.44965, 'poiId': 332108, 'shopId': 3671251}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,015 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 15270, 'cityId': 1, 'name': '首都电影院（中华店 中国巨幕）', 'addr': '西城区天桥南大街3号楼一层、二层', 'lat': 39.884457, 'lng': 116.398186, 'poiId': 93439511, 'shopId': 58220418}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,025 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 259, 'cityId': 1, 'name': '紫光影城（蓝岛店）', 'addr': '朝阳区朝外大街8号（蓝岛大厦西区5-6层）', 'lat': 39.922626, 'lng': 116.44817, 'poiId': 3274641, 'shopId': 1917295}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,026 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 16179, 'cityId': 1, 'name': '米瑞酷影城（日坛店）', 'addr': '朝阳区日坛国际酒店地下一层', 'lat': 39.920116, 'lng': 116.44342, 'poiId': 108119917, 'shopId': 69091841}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,027 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 16605, 'cityId': 1, 'name': '传奇奢华影城', 'addr': '东城区东打磨厂街7号新活馆B1层', 'lat': 39.899563, 'lng': 116.41362, 'poiId': 1460422, 'shopId': 5696134}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,028 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 24580, 'cityId': 1, 'name': '万达影城（西铁营万达广场店）', 'addr': '丰台区西铁营中路1号万达广场七层万达影城', 'lat': 39.86078, 'lng': 116.35673, 'poiId': 164912365, 'shopId': 97996408}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,029 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 27343, 'cityId': 1, 'name': '新影联美亚东申影城', 'addr': '房山区学园北街26号院1号楼北京时代广场一层', 'lat': 39.72452, 'lng': 116.1739, 'poiId': 194634103, 'shopId': 131659741}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,030 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 13028, 'cityId': 1, 'name': '幸福蓝海国际影城（北京房山店）', 'addr': '房山区广阳新路9号院1号楼中粮万科半岛购物广场3层', 'lat': 39.75359, 'lng': 116.20994, 'poiId': 40470614, 'shopId': 23090717}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,031 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 116, 'cityId': 1, 'name': '博纳国际影城（朝阳门IMAX店）', 'addr': '朝阳区三丰北里2号悠唐购物中心二期B1层', 'lat': 39.922028, 'lng': 116.43903, 'poiId': 63, 'shopId': 3212818}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,032 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 14384, 'cityId': 1, 'name': '中影国际影城（丰台永旺店）', 'addr': '丰台区丰葆路永旺梦乐城4层', 'lat': 39.81777, 'lng': 116.29251, 'poiId': 77423086, 'shopId': 27331304}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,033 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 132, 'cityId': 1, 'name': '珠影耳东传奇影城', 'addr': '朝阳区朝阳公园路6号蓝色港湾国际商区SA-42（朝阳公园西北角）', 'lat': 39.94892, 'lng': 116.476204, 'poiId': 297916, 'shopId': 2886442}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,034 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 24061, 'cityId': 1, 'name': '中都影城（王府井百货右安门店）', 'addr': '西城区万博苑王府井购物中心五楼', 'lat': 39.8719, 'lng': 116.36495, 'poiId': 162727173, 'shopId': 95935848}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,035 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 16655, 'cityId': 1, 'name': '万达影城（丰台店）', 'addr': '丰台区丰科路6号万达广场6层', 'lat': 39.824207, 'lng': 116.29894, 'poiId': 122443680, 'shopId': 76759096}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,036 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 136, 'cityId': 1, 'name': '美嘉欢乐影城（三里屯店）', 'addr': '朝阳区三里屯北路19号三里屯太古里南区B1层', 'lat': 39.93486, 'lng': 116.45441, 'poiId': 30915, 'shopId': 2635636}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,036 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 269, 'cityId': 1, 'name': '百老汇影城（东方广场店）', 'addr': '东城区东长安街1号东方新天地LG层第五区', 'lat': 39.909874, 'lng': 116.41683, 'poiId': 271409, 'shopId': 1767619}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,037 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 35770, 'cityId': 1, 'name': '森美国际影城（房山店）', 'addr': '房山区北京市长阳地铁站南侧金泰广场4楼', 'lat': 39.761242, 'lng': 116.212654, 'poiId': 741371984, 'shopId': 741371984}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,039 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 263, 'cityId': 1, 'name': '大观楼电影院', 'addr': '西城区前门大街大栅栏街36号', 'lat': 39.895596, 'lng': 116.39515, 'poiId': 89010, 'shopId': 1767601}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,040 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 13640, 'cityId': 1, 'name': '艾米·1895电影街', 'addr': '朝阳区工体北路13号世茂工三3楼，艾米·1895电影街（三里屯商圈）', 'lat': 39.934387, 'lng': 116.44968, 'poiId': 42853106, 'shopId': 22182457}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,041 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 17023, 'cityId': 1, 'name': '保利国际影城（天安门店）', 'addr': '西城区煤市街廊房头条交叉口东北角北京坊东区B1-B2层', 'lat': 39.898144, 'lng': 116.397354, 'poiId': 150609037, 'shopId': 77560267}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,042 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 122, 'cityId': 1, 'name': '新影联金宝汇影城', 'addr': '东城区金宝街88号金宝汇购物中心一期7层', 'lat': 39.9152, 'lng': 116.42129, 'poiId': 1076058, 'shopId': 3088969}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,043 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 17169, 'cityId': 1, 'name': '乐糖影城（房山店）', 'addr': '房山区长阳地铁站南侧京投港购物中心5层', 'lat': 39.763165, 'lng': 116.21307, 'poiId': 152404744, 'shopId': 79304786}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,044 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 254, 'cityId': 1, 'name': '枫花园汽车电影院（朝阳公园店）', 'addr': '朝阳区亮马桥路21号（朝阳公园北门对面）', 'lat': 39.957985, 'lng': 116.48087, 'poiId': 271415, 'shopId': 1767643}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,045 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 16813, 'cityId': 1, 'name': '美都影城工体店', 'addr': '朝阳区工体北路21号永利国际购物中心B1', 'lat': 39.934322, 'lng': 116.44454, 'poiId': 150108303, 'shopId': 77041298}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,045 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 27272, 'cityId': 1, 'name': '星典影城（亮马桥四季店）', 'addr': '朝阳区亮马桥路48号', 'lat': 39.9503, 'lng': 116.46694, 'poiId': 193978484, 'shopId': 131009232}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,046 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 267, 'cityId': 1, 'name': '百老汇影城（apm购物中心店）', 'addr': '东城区王府井大街138号北京apm6层', 'lat': 39.91409, 'lng': 116.41183, 'poiId': 271444, 'shopId': 1767763}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,047 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 79, 'cityId': 1, 'name': '横店电影城（王府井店）', 'addr': '东城区王府井大街255号北京市百货大楼北馆8层', 'lat': 39.913956, 'lng': 116.41032, 'poiId': 1549949, 'shopId': 4119878}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,048 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 8, 'cityId': 1, 'name': 'CGV星星影城（颐堤港ScreenX店）', 'addr': '朝阳区酒仙桥路18号颐堤港4层（将台地铁站）', 'lat': 39.97011, 'lng': 116.4919, 'poiId': 1466992, 'shopId': 4277875}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,049 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 16467, 'cityId': 1, 'name': '华谊兄弟电影汇', 'addr': '朝阳区新源南路甲2号华谊兄弟办公楼首层', 'lat': 39.94859, 'lng': 116.45831, 'poiId': 112208438, 'shopId': 73387985}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,050 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 265, 'cityId': 1, 'name': '新影联东环影城', 'addr': '东城区东中街9号东环广场B座B1楼', 'lat': 39.936527, 'lng': 116.436066, 'poiId': 43786, 'shopId': 1767625}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,051 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 247, 'cityId': 1, 'name': '广安门电影院', 'addr': '西城区白广路8号', 'lat': 39.884075, 'lng': 116.35917, 'poiId': 82592, 'shopId': 1767652}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,052 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 35998, 'cityId': 1, 'name': '新影联米瑞酷影城（酒仙桥店）', 'addr': '朝阳区酒仙桥路12号毕淘买商场3楼', 'lat': 39.97553, 'lng': 116.49008, 'poiId': 652432807, 'shopId': 652432807}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,053 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 181, 'cityId': 1, 'name': '中国电影博物馆', 'addr': '朝阳区南影路9号（近798）', 'lat': 39.9962, 'lng': 116.521, 'poiId': 1436410, 'shopId': 2115112}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,054 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 242, 'cityId': 1, 'name': '东宫影剧院', 'addr': '东城区隆福寺街47号东四工人文化宫', 'lat': 39.9253, 'lng': 116.41552, 'poiId': 60166, 'shopId': 1767622}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,055 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 25125, 'cityId': 1, 'name': '三克影院（来福士店）', 'addr': '东城区东直门来福士购物中心5层', 'lat': 39.940186, 'lng': 116.43246, 'poiId': 165735819, 'shopId': 98770377}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,056 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 25256, 'cityId': 1, 'name': '咪咚影院（良乡店）', 'addr': '房山区拱辰南大街7号院1号楼良辰百货4层', 'lat': 39.728836, 'lng': 116.14166, 'poiId': 169653614, 'shopId': 102664892}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,057 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 27189, 'cityId': 1, 'name': '万达影城（房山首创奥莱店）', 'addr': '房山区首创奥特莱斯广场', 'lat': 39.764805, 'lng': 116.184296, 'poiId': 193725332, 'shopId': 130758861}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,058 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 2081, 'cityId': 1, 'name': '橙天嘉禾影城（凤凰汇店）', 'addr': '朝阳区曙光西里甲5号院24号楼凤凰汇三层', 'lat': 39.963345, 'lng': 116.457664, 'poiId': 1465641, 'shopId': 5477181}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,059 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 94, 'cityId': 1, 'name': '百老汇电影中心（万国城店）', 'addr': '东城区香河园路1号当代MOMA北区T4座（近东直门公交枢纽）', 'lat': 39.950474, 'lng': 116.43806, 'poiId': 1076062, 'shopId': 3129577}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,060 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 48, 'cityId': 1, 'name': '完美世界影城（北京比如店）', 'addr': '朝阳区京顺路111号比如世界购物中心1层（近太阳宫北街）', 'lat': 39.9684, 'lng': 116.462036, 'poiId': 75603, 'shopId': 4206977}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,061 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 131, 'cityId': 1, 'name': '新华国际影城（房山店）', 'addr': '房山区良乡北关西路14号华冠购物中心五层（良乡医院对面）', 'lat': 39.735233, 'lng': 116.13934, 'poiId': 299222, 'shopId': 2926645}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,062 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 145, 'cityId': 1, 'name': '良乡影剧院', 'addr': '房山区良乡拱辰大街31号', 'lat': 39.73799, 'lng': 116.141685, 'poiId': 1436368, 'shopId': 1767697}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,063 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 149, 'cityId': 1, 'name': '首都电影院（西单店 LED+LUXE）', 'addr': '西城区西单北大街131号大悦城10楼（近西单苹果店）', 'lat': 39.910625, 'lng': 116.37323, 'poiId': 283722, 'shopId': 2407390}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,064 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 5278, 'cityId': 1, 'name': '耀莱成龙影城（马连道店）', 'addr': '西城区马连道路25号新年华生活购物广场5层', 'lat': 39.877087, 'lng': 116.32533, 'poiId': 2393654, 'shopId': 8075953}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,065 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 26332, 'cityId': 1, 'name': '中影CFR国际影城（望京万科时代中心店）', 'addr': '朝阳区望京街9号万科时代中心F座B1层', 'lat': 39.989162, 'lng': 116.48319, 'poiId': 190314402, 'shopId': 127529502}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,066 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 13618, 'cityId': 1, 'name': 'SFC上影影城（房山绿地缤纷城店）', 'addr': '房山区黄辛庄路口绿地缤纷城3层', 'lat': 39.756683, 'lng': 116.160515, 'poiId': 52294367, 'shopId': 61365379}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,067 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 16683, 'cityId': 1, 'name': '莱纳金唐影城（原北京莱纳恒泰影城）', 'addr': '丰台区北京市丰台北路18号院金唐购物中心6层（地铁西局站）', 'lat': 39.86605, 'lng': 116.30508, 'poiId': 125611088, 'shopId': 76847827}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,067 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 26198, 'cityId': 1, 'name': '奥兰环球影城（方恒购物中心一店）', 'addr': '朝阳区阜通东大街6号院4号楼方恒购物中心', 'lat': 39.99019, 'lng': 116.48251, 'poiId': 189708612, 'shopId': 126973420}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,068 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 26197, 'cityId': 1, 'name': '奥兰环球影城（方恒购物中心二店）', 'addr': '朝阳区阜通东大街6号院4号楼四层4-02至4-15', 'lat': 39.990215, 'lng': 116.48242, 'poiId': 189720568, 'shopId': 126972745}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,069 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 25288, 'cityId': 1, 'name': '耀莱成龙影城（丽泽桥店）', 'addr': '丰台区西三环南路甲27号居然之家5层', 'lat': 39.872055, 'lng': 116.30988, 'poiId': 170668636, 'shopId': 103672522}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,071 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 25747, 'cityId': 1, 'name': '耀莱成龙影城（房山天街店）', 'addr': '房山区政通南路2号院1号楼龙湖房山天街五层', 'lat': 39.745777, 'lng': 116.14136, 'poiId': 182505168, 'shopId': 120164141}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,072 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 15280, 'cityId': 1, 'name': '青春光线电影院', 'addr': '东城区滨河路乙1号雍和航星园74-76号楼', 'lat': 39.9512, 'lng': 116.42075, 'poiId': 99389254, 'shopId': 58556187}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,073 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 36575, 'cityId': 1, 'name': '完美世界影城（北京太阳宫店）', 'addr': '朝阳区太阳宫中路12号楼5层01、05号', 'lat': 39.97144, 'lng': 116.44745, 'poiId': 1895423790, 'shopId': 1895423790}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,074 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 24963, 'cityId': 1, 'name': '星典影城（六里桥店）', 'addr': '丰台区西三环六里桥南里月恒正大商场三层（原卜蜂莲花超市）', 'lat': 39.87878, 'lng': 116.31276, 'poiId': 165605811, 'shopId': 98637752}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,075 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 261, 'cityId': 1, 'name': '地质礼堂', 'addr': '西城区西四羊肉胡同30号（中国地质博物馆南侧）', 'lat': 39.92254, 'lng': 116.37134, 'poiId': 89006, 'shopId': 1767610}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,076 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 39, 'cityId': 1, 'name': '万达影城（望京保利光魔店）', 'addr': '朝阳区望京阜通西大街新荟城购物中心五层（近橄榄城）', 'lat': 39.998497, 'lng': 116.481926, 'poiId': 1107541, 'shopId': 4232140}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,076 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 1625, 'cityId': 1, 'name': '首都电影院（金融街店 杜比全景声）', 'addr': '西城区金城坊街2号金融街购物中心2期B1层', 'lat': 39.915573, 'lng': 116.36036, 'poiId': 1541415, 'shopId': 5402295}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,077 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 7881, 'cityId': 1, 'name': '大地影院（北京合生麒麟新天地店）', 'addr': '朝阳区阜通西大街11号合生·麒麟新天地2层', 'lat': 39.99706, 'lng': 116.47777, 'poiId': 4036242, 'shopId': 15099144}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,078 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 35745, 'cityId': 1, 'name': '万画影城 （国投财富广场店）', 'addr': '丰台区广安路9号院11号楼地下一层1217-08', 'lat': 39.891666, 'lng': 116.322815, 'poiId': 838686599, 'shopId': 838686599}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,079 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 28425, 'cityId': 1, 'name': '中都影城（长安商场店）', 'addr': '西城区复兴门外大街长安商场4层中都影城', 'lat': 39.907772, 'lng': 116.34524, 'poiId': 656953913, 'shopId': 656953913}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,080 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 35987, 'cityId': 1, 'name': '新影联米瑞酷影城（顺义店）', 'addr': '顺义区顺平西路3号2幢一层210号', 'lat': 40.118458, 'lng': 116.655655, 'poiId': 669132666, 'shopId': 669132666}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,081 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 256, 'cityId': 1, 'name': '金鸡百花影城', 'addr': '朝阳区北三环东路22号（和平东桥，和平东街，樱花东街）', 'lat': 39.96894, 'lng': 116.42397, 'poiId': 89000, 'shopId': 1767790}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,082 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 16638, 'cityId': 1, 'name': '恒业影城北京IMAX店', 'addr': '丰台区万丰路（地铁9号线、10号线六里桥站）银座和谐广场购物中心5F', 'lat': 39.882187, 'lng': 116.29706, 'poiId': 133660718, 'shopId': 76672259}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,083 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 25163, 'cityId': 1, 'name': '晟嘉国际影城（月坛万方店）', 'addr': '西城区月坛南街30号万方西单商场', 'lat': 39.913937, 'lng': 116.341034, 'poiId': 166012764, 'shopId': 99048791}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,084 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 17139, 'cityId': 1, 'name': '明星时代影城（梦秀店）', 'addr': '朝阳区望京西路41号梦秀商场6层', 'lat': 39.994465, 'lng': 116.45678, 'poiId': 152364320, 'shopId': 79269765}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,085 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 36658, 'cityId': 1, 'name': '中影盛世华纳国际影城', 'addr': '顺义区顺西南路丙2号院', 'lat': 40.115948, 'lng': 116.64169, 'poiId': 1957886488, 'shopId': 1957886488}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,087 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 99, 'cityId': 1, 'name': 'UME影城（安贞DTS:X店）', 'addr': '东城区北三环东路36号环球贸易中心E座1层', 'lat': 39.966072, 'lng': 116.410965, 'poiId': 94496, 'shopId': 3487045}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,088 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 69, 'cityId': 1, 'name': '博纳国际影城（顺义店）', 'addr': '顺义区新顺南大街18号新世界百货七层', 'lat': 40.126827, 'lng': 116.65199, 'poiId': 1437402, 'shopId': 4186758}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,089 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 12394, 'cityId': 1, 'name': '大地影院（北京顺义隆华CINITY店）', 'addr': '顺义区新顺南大街11号隆华购物中心6F', 'lat': 40.126514, 'lng': 116.65033, 'poiId': 41599879, 'shopId': 19438612}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,090 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 72, 'cityId': 1, 'name': '新影联·华谊兄弟影院（望京店）', 'addr': '朝阳区广顺北大街16号望京华彩商业中心B1a', 'lat': 40.01051, 'lng': 116.46821, 'poiId': 82583, 'shopId': 3463600}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,091 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 8111, 'cityId': 1, 'name': 'CGV影城（顺义ScreenX店）', 'addr': '顺义区新顺南大街8号华联购物中心4层', 'lat': 40.128777, 'lng': 116.65279, 'poiId': 6448554, 'shopId': 15926029}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,092 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 252, 'cityId': 1, 'name': '中国木偶艺术剧院', 'addr': '朝阳区安华西里甲1号', 'lat': 39.96802, 'lng': 116.40147, 'poiId': 82596, 'shopId': 2007820}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,093 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 25061, 'cityId': 1, 'name': '晟嘉国际影城（新华百货店）', 'addr': '西城区新街口北大街1号新华百货5层', 'lat': 39.947483, 'lng': 116.37118, 'poiId': 165629027, 'shopId': 98672102}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,094 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 28301, 'cityId': 1, 'name': '澜创嘉映影城（远洋未来广场店）', 'addr': '朝阳区北四环东路远洋未来广场4层', 'lat': 39.990177, 'lng': 116.43237, 'poiId': 887376462, 'shopId': 887376462}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,095 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 7634, 'cityId': 1, 'name': '中影国际影城（丰台千禧街店）', 'addr': '丰台区靛厂路千禧商业街4号楼', 'lat': 39.889786, 'lng': 116.287766, 'poiId': 6458108, 'shopId': 8905548}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,096 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 9916, 'cityId': 1, 'name': '中影国际影城小西天中国巨幕头等舱', 'addr': '海淀区新街口外大街25号（小西天牌楼北侧）', 'lat': 39.95296, 'lng': 116.37117, 'poiId': 82594, 'shopId': 1767805}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,097 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 25196, 'cityId': 1, 'name': '华夏影城（环宇荟店）', 'addr': '朝阳区安定路6号环宇荟5层（安贞门地铁站B口）', 'lat': 39.977654, 'lng': 116.40644, 'poiId': 164780255, 'shopId': 97883827}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,098 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 27612, 'cityId': 1, 'name': '完美世界影城（西直门凯德mall店）', 'addr': '西城区西直门外大街1号西区商业凯德mall商城5层41号', 'lat': 39.941696, 'lng': 116.3533, 'poiId': 947180083, 'shopId': 947180083}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,099 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 16421, 'cityId': 1, 'name': '奥兰环球影城（望京店）', 'addr': '朝阳区来广营西路 5号院诚盈中心6号楼B1层商业街', 'lat': 40.02186, 'lng': 116.46508, 'poiId': 106343887, 'shopId': 67709984}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,100 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 154, 'cityId': 1, 'name': '1+x电影生活空间今典花园店（原17.5影城）', 'addr': '海淀区文慧园北路9号今典花园9号二层', 'lat': 39.95334, 'lng': 116.361046, 'poiId': 273950, 'shopId': 1896709}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,101 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 1624, 'cityId': 1, 'name': '博纳国际影城（万寿路店）', 'addr': '海淀区复兴路51号凯德晶品购物中心4层', 'lat': 39.908405, 'lng': 116.29659, 'poiId': 1460949, 'shopId': 5552714}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,102 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 27000, 'cityId': 1, 'name': '中影千人影城（丰台集美广场店）', 'addr': '丰台区卢沟桥村杜家坎环岛北侧集美家居4层', 'lat': 39.845463, 'lng': 116.21023, 'poiId': 192352126, 'shopId': 129504246}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,103 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 248, 'cityId': 1, 'name': '北京剧院', 'addr': '朝阳区安慧里三区10号（近慧忠路）', 'lat': 39.99109, 'lng': 116.40853, 'poiId': 82597, 'shopId': 2080306}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,104 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 26463, 'cityId': 1, 'name': '唐阁影城（丰台京荟广场店）', 'addr': '丰台区小屯村梅市口路北侧133号京荟广场B座301房间', 'lat': 39.881092, 'lng': 116.25096, 'poiId': 190798068, 'shopId': 127990491}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,105 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 13003, 'cityId': 1, 'name': '天幕新彩云国际影城', 'addr': '海淀区北三环中路中视云投大厦（北太平桥西远望楼宾馆中央新影集团）', 'lat': 39.969345, 'lng': 116.3678, 'poiId': 4480546, 'shopId': 17145824}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,106 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 25987, 'cityId': 1, 'name': '博纳国际影城（亚运村店）', 'addr': '朝阳区安立路68号太阳飘亮购物中心B1层', 'lat': 39.99798, 'lng': 116.409195, 'poiId': 187546094, 'shopId': 124881591}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,107 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 25958, 'cityId': 1, 'name': '深影国际影城（学院南路店）', 'addr': '海淀区学院南路50号哇沃生活广场3楼', 'lat': 39.957626, 'lng': 116.348564, 'poiId': 186965947, 'shopId': 124328264}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,108 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 31, 'cityId': 1, 'name': '活力天宝国际影城', 'addr': '朝阳区祁家豁子8号健翔大厦家乐福超市B1层', 'lat': 39.980343, 'lng': 116.38112, 'poiId': 1098864, 'shopId': 5189980}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,109 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 23617, 'cityId': 1, 'name': '金泉港IMAX国际影城', 'addr': '朝阳区大屯里金泉购物中心318号楼4层', 'lat': 40.00447, 'lng': 116.41641, 'poiId': 158732678, 'shopId': 91956468}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,109 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 238, 'cityId': 1, 'name': '国图影院', 'addr': '海淀区中关村南大街33号国家图书馆内', 'lat': 39.944195, 'lng': 116.32412, 'poiId': 271442, 'shopId': 2447194}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,111 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 25, 'cityId': 1, 'name': '完美世界影城（北京四道口店）', 'addr': '海淀区大钟寺四道口2号京果商厦B座三层北侧', 'lat': 39.959652, 'lng': 116.3457, 'poiId': 48958, 'shopId': 5175082}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,111 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 11102, 'cityId': 1, 'name': '橙天嘉禾影城（北京祥云CINITY店）', 'addr': '顺义区安泰大街9号院7号楼二层（祥云小镇内）', 'lat': 40.089844, 'lng': 116.53675, 'poiId': 40420215, 'shopId': 20766928}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,112 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 9370, 'cityId': 1, 'name': '环球国际影城（房山欢乐城店）', 'addr': '房山区兴房大街38号华冠欢乐城四楼', 'lat': 39.69293, 'lng': 115.987305, 'poiId': 5252975, 'shopId': 21601900}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,113 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 65, 'cityId': 1, 'name': 'CGV星星影城（奥体店）', 'addr': '朝阳区湖景东路11号新奥购物中心B1-B2楼（奥体公园玲珑塔旁）', 'lat': 39.999462, 'lng': 116.39392, 'poiId': 360511, 'shopId': 4225037}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,114 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 40, 'cityId': 1, 'name': '保利国际影城（中国科技馆店）', 'addr': '朝阳区北辰东路5号（鸟巢正北一公里）', 'lat': 40.00603, 'lng': 116.39888, 'poiId': 61574, 'shopId': 3792178}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,115 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 36720, 'cityId': 1, 'name': '中影奥兰环球影城（顺义LUXE店）', 'addr': '顺义区顺恒大街10号院5号楼2层201', 'lat': 40.180428, 'lng': 116.65951, 'poiId': 1559073803, 'shopId': 1559073803}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,116 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 26537, 'cityId': 1, 'name': '北京ACE影城（后沙LUXE店）', 'addr': '顺义区后沙峪安平街5号院国门一号国际馆1号楼四层ACE影城', 'lat': 40.119186, 'lng': 116.55929, 'poiId': 191131831, 'shopId': 128315356}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,117 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 26411, 'cityId': 1, 'name': '大地影院（鲁能美丽汇店）', 'addr': '顺义区马坡镇鲁能美丽汇3层', 'lat': 40.178867, 'lng': 116.65142, 'poiId': 190615697, 'shopId': 127828439}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,118 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 25270, 'cityId': 1, 'name': '元影城', 'addr': '朝阳区安立路28号院华创生活广场1层', 'lat': 40.026527, 'lng': 116.41191, 'poiId': 170567772, 'shopId': 103571723}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,119 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 155, 'cityId': 1, 'name': 'UME影城（华星IMAX店）', 'addr': '海淀区双榆树科学院南路44号（双安商场对面）', 'lat': 39.967793, 'lng': 116.326096, 'poiId': 1436373, 'shopId': 1767676}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,120 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 28124, 'cityId': 1, 'name': '时光巨幕影城房山店', 'addr': '房山区城关街道万宁桥南侧100米未来小镇二层', 'lat': 39.70859, 'lng': 115.984375, 'poiId': 1269846746, 'shopId': 1269846746}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,121 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 21, 'cityId': 1, 'name': 'K酷国际影城', 'addr': '朝阳区北苑路42号卜峰莲花超市4楼（K酷时尚广场）', 'lat': 40.033386, 'lng': 116.41916, 'poiId': 796845, 'shopId': 5342775}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,122 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 36517, 'cityId': 1, 'name': '魔影国际影城（吉彩店）', 'addr': '海淀区玉海园五里22号配套商业楼', 'lat': 39.92276, 'lng': 116.25957, 'poiId': 1752846104, 'shopId': 1752846104}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,123 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 2603, 'cityId': 1, 'name': '保利国际影城（华贸天地店）', 'addr': '朝阳区清河营南街七号院华贸天地东区B2层', 'lat': 40.04777, 'lng': 116.4308, 'poiId': 361205, 'shopId': 4232132}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,124 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 133, 'cityId': 1, 'name': '万达影城（石景山店）', 'addr': '石景山区石景山路乙18号万达广场娱乐楼4楼', 'lat': 39.905945, 'lng': 116.22568, 'poiId': 298683, 'shopId': 2908582}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,125 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 23901, 'cityId': 1, 'name': '朗克影城', 'addr': '朝阳区林萃西里16号楼华创生活广场F1层', 'lat': 40.010098, 'lng': 116.37261, 'poiId': 160306126, 'shopId': 93539031}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,126 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 257, 'cityId': 1, 'name': '海淀剧院', 'addr': '海淀区中关村大街28号', 'lat': 39.97669, 'lng': 116.31822, 'poiId': 17899, 'shopId': 2020426}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,127 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 16821, 'cityId': 1, 'name': '万画影城（田村店）', 'addr': '海淀区田村路43号京粮广场二层北侧', 'lat': 39.931076, 'lng': 116.25355, 'poiId': 97764971, 'shopId': 62248491}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,128 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 13054, 'cityId': 1, 'name': '万画影城（四季青店）', 'addr': '海淀区西四环北路金四季购物中心中段三层B003', 'lat': 39.94469, 'lng': 116.27136, 'poiId': 41066531, 'shopId': 23325693}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,129 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 17421, 'cityId': 1, 'name': '太平洋影城（北京中关村店）', 'addr': '海淀区融科资讯中心B座-1-2', 'lat': 39.98476, 'lng': 116.32643, 'poiId': 158401435, 'shopId': 91625813}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,130 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 271, 'cityId': 1, 'name': '英嘉国际影城（金源NEW CINITY店）', 'addr': '海淀区远大路1号金源时代购物中心5楼东首（近蓝靛厂北路）', 'lat': 39.95867, 'lng': 116.2889, 'poiId': 271447, 'shopId': 1767778}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,130 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 152, 'cityId': 1, 'name': '金逸影城（中关村店）', 'addr': '海淀区中关村大街19号新中关购物中心B1层', 'lat': 39.978386, 'lng': 116.31446, 'poiId': 276722, 'shopId': 2032099}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,131 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 17304, 'cityId': 1, 'name': '魔影国际影城（金源店）', 'addr': '海淀区远大路1号院B座五楼西侧001号（居然之家材料馆楼上）', 'lat': 39.960518, 'lng': 116.28797, 'poiId': 156803662, 'shopId': 90039204}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,133 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 23612, 'cityId': 1, 'name': '恒华国际影城（顺义店）', 'addr': '顺义区牛栏山镇恒华西街2号院3号楼5层', 'lat': 40.20238, 'lng': 116.6551, 'poiId': 158695144, 'shopId': 91916495}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,134 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 70, 'cityId': 1, 'name': '嘉华国际影城（学清路店）', 'addr': '海淀区学清路甲8号圣熙8号购物中心5层西侧（学清路）', 'lat': 40.00859, 'lng': 116.35387, 'poiId': 84440, 'shopId': 4211150}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,134 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 141, 'cityId': 1, 'name': '海淀工人文化宫', 'addr': '海淀区万柳华府北街2号（万柳华联商城南门对面）', 'lat': 39.971443, 'lng': 116.2951, 'poiId': 38025, 'shopId': 2620297}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,135 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 28417, 'cityId': 1, 'name': '华联影院（原橙天嘉禾万柳店）', 'addr': '海淀区巴沟路2号华联万柳购物中心5层', 'lat': 39.97273, 'lng': 116.29506, 'poiId': 604861930, 'shopId': 604861930}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,136 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 9914, 'cityId': 1, 'name': '星环影城（立水桥店）', 'addr': '朝阳区立汤路201号东亚奥北南区北门一楼（华泰汽车斜对面，立水桥地铁A口北行150米）', 'lat': 40.054523, 'lng': 116.41205, 'poiId': 3260787, 'shopId': 18589562}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,137 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 28331, 'cityId': 1, 'name': '耳东影城天通苑店', 'addr': '昌平区东小口镇天通苑东苑东三区2号楼国泰百货4层TC-103', 'lat': 40.07303, 'lng': 116.43582, 'poiId': 793966266, 'shopId': 793966266}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,138 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 151, 'cityId': 1, 'name': '万达影城（龙德广场店）', 'addr': '昌平区立汤路186号龙德广场5层', 'lat': 40.060596, 'lng': 116.41618, 'poiId': 30864, 'shopId': 2411398}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,139 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 5359, 'cityId': 1, 'name': '新华国际影城（宝盛店）', 'addr': '海淀区宝盛北里西区28号兴美生活广场5层', 'lat': 40.03706, 'lng': 116.370605, 'poiId': 2408760, 'shopId': 8021659}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,140 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 36339, 'cityId': 1, 'name': '中影南方古城影院', 'addr': '石景山区古城南路甲21号院古城影院', 'lat': 39.91134, 'lng': 116.19093, 'poiId': 825521075, 'shopId': 825521075}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,141 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 26649, 'cityId': 1, 'name': '中影星美国际影城（天通苑店）', 'addr': '昌平区东小口镇天通苑西三区天通尾货3层', 'lat': 40.074417, 'lng': 116.410225, 'poiId': 191228472, 'shopId': 128418568}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,142 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 9459, 'cityId': 1, 'name': '中间影院', 'addr': '海淀区杏石口路中间艺术园区内（中间艺术园区内）', 'lat': 39.953655, 'lng': 116.230934, 'poiId': 4572438, 'shopId': 18354387}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,143 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 5111, 'cityId': 1, 'name': 'CGV影城（清河IMAX店）', 'addr': '海淀区清河中街68号清河万象汇东区7层', 'lat': 40.03054, 'lng': 116.33629, 'poiId': 2374984, 'shopId': 4277880}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,144 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 25045, 'cityId': 1, 'name': '东融国际影城（西小口店）', 'addr': '海淀区文龙家园四里4号楼4F-08', 'lat': 40.04362, 'lng': 116.35009, 'poiId': 165628440, 'shopId': 98668294}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,145 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 26808, 'cityId': 1, 'name': '耀莱成龙影城（玉泉山店）', 'addr': '海淀区北坞嘉园南里35号楼玉泉商业生活中心', 'lat': 39.97615, 'lng': 116.25158, 'poiId': 191417722, 'shopId': 128617885}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,146 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 58, 'cityId': 1, 'name': '金逸影城（新都店）', 'addr': '海淀区西三旗建材城中路6号新都购物广场1层', 'lat': 40.059204, 'lng': 116.3653, 'poiId': 1549060, 'shopId': 4519054}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,147 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 10294, 'cityId': 1, 'name': '保利国际影城（苹果园店）', 'addr': '石景山区阜石路300号喜隆多三层', 'lat': 39.923206, 'lng': 116.171295, 'poiId': 6596632, 'shopId': 19214050}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,148 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 27962, 'cityId': 1, 'name': '华联影城（上地店）', 'addr': '海淀区上地南口华联商厦4F（近上地南口）', 'lat': 40.028584, 'lng': 116.3117, 'poiId': 1608545587, 'shopId': 1608545587}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,150 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 7433, 'cityId': 1, 'name': '大地影院（西三旗物美店）', 'addr': '海淀区悦秀路99号二层', 'lat': 40.04745, 'lng': 116.33781, 'poiId': 4845675, 'shopId': 13748743}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,151 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 24340, 'cityId': 1, 'name': '博纳国际影城（密云店）', 'addr': '密云区滨河路178号万象汇购物中心4层', 'lat': 40.356407, 'lng': 116.836205, 'poiId': 164442351, 'shopId': 97544556}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,152 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 27986, 'cityId': 1, 'name': '博纳国际影城（门头沟店）', 'addr': '门头沟区新城东街17号院2号楼5层Z05号、6层Z01号（地铁s1线上岸站B口出）', 'lat': 39.90609, 'lng': 116.12312, 'poiId': 1928126412, 'shopId': 1928126412}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,154 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 5502, 'cityId': 1, 'name': '保利国际影城（龙旗广场店）', 'addr': '昌平区黄平路19号院3号楼龙旗广场购物中心3层（地铁8号线育新站路北600米，近永辉超市）', 'lat': 40.066605, 'lng': 116.346725, 'poiId': 3320660, 'shopId': 7999526}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,155 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 25172, 'cityId': 1, 'name': '华联影城（肖家河店）', 'addr': '海淀区龙背村路99号院北京华联龙背购物中心', 'lat': 40.015923, 'lng': 116.27105, 'poiId': 166727606, 'shopId': 100034560}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,157 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 27811, 'cityId': 1, 'name': '东影时代影城（密云店）', 'addr': '密云区鼓楼南大街22号4层', 'lat': 40.371964, 'lng': 116.84601, 'poiId': 1702945396, 'shopId': 1702945396}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,159 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 16595, 'cityId': 1, 'name': '米瑞酷国际影城（密云店）', 'addr': '密云区鼓楼南大街10号瑞嘉商场4层', 'lat': 40.374863, 'lng': 116.846085, 'poiId': 112400372, 'shopId': 74582589}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,160 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 9647, 'cityId': 1, 'name': '沃美影城（回龙观店）', 'addr': '昌平区回龙观同成街华联购物中心四楼（城铁回龙观站出口对面）', 'lat': 40.071976, 'lng': 116.33718, 'poiId': 4058821, 'shopId': 18049661}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,161 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 10570, 'cityId': 1, 'name': '幸福蓝海影城（门头沟店）', 'addr': '门头沟区永定镇冯村华润购物中心2层', 'lat': 39.91212, 'lng': 116.11124, 'poiId': 42297501, 'shopId': 19790392}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,162 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 25814, 'cityId': 1, 'name': '莱纳龙域影城', 'addr': '昌平区龙域中街1号院1号楼昌发展万科广场5层', 'lat': 40.066483, 'lng': 116.31665, 'poiId': 184222752, 'shopId': 121712698}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,163 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 25016, 'cityId': 1, 'name': '中影星美国际影城（温都水城店）', 'addr': '昌平区北七家镇温都水城广场4-5层', 'lat': 40.106285, 'lng': 116.37212, 'poiId': 165628212, 'shopId': 98654863}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,164 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 25346, 'cityId': 1, 'name': '华联影院（回龙观店）', 'addr': '昌平区回龙观镇西大街111号三层F3-90', 'lat': 40.076687, 'lng': 116.31893, 'poiId': 175463726, 'shopId': 108306020}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,165 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 10979, 'cityId': 1, 'name': '熙旺国际影城', 'addr': '门头沟区双峪路35号熙旺生活广场B座6层（物美大卖场楼上）', 'lat': 39.9358, 'lng': 116.113716, 'poiId': 40550440, 'shopId': 21163339}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,166 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 182, 'cityId': 1, 'name': '门头沟影剧院', 'addr': '门头沟区新桥大街12号', 'lat': 39.942497, 'lng': 116.10049, 'poiId': 3260641, 'shopId': 1767700}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,167 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 24260, 'cityId': 1, 'name': '唐阁影城（怀柔星东天地店免费停车）', 'addr': '怀柔区开放东路13号院2号楼', 'lat': 40.32301, 'lng': 116.65101, 'poiId': 163859137, 'shopId': 97086194}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,168 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 107, 'cityId': 1, 'name': '中影国际影城（昌平永旺店）', 'addr': '昌平区北清路1号永旺国际商城3楼', 'lat': 40.09749, 'lng': 116.288574, 'poiId': 82598, 'shopId': 3463180}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,169 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 26195, 'cityId': 1, 'name': '大地院线影城（珠江摩尔店）', 'addr': '昌平区回龙观镇北清路1号院7号楼内7-101-26', 'lat': 40.09799, 'lng': 116.287895, 'poiId': 189719766, 'shopId': 126972484}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,170 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 24662, 'cityId': 1, 'name': '万达影城（怀柔万达广场店）', 'addr': '怀柔区府前西街1号院1号楼万达广场7层', 'lat': 40.316025, 'lng': 116.6302, 'poiId': 165035028, 'shopId': 98125104}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,171 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 55, 'cityId': 1, 'name': 'IDA传奇影城（怀柔店）', 'addr': '怀柔区青春路15号四层', 'lat': 40.317955, 'lng': 116.62986, 'poiId': 3260663, 'shopId': 5331383}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,172 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 16823, 'cityId': 1, 'name': '环球国际影城（怀柔店）', 'addr': '怀柔区开放路泉河园二区乙二号楼一层环球国际影城（下元市场北150米）', 'lat': 40.32895, 'lng': 116.64552, 'poiId': 150309419, 'shopId': 77219186}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,173 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 16285, 'cityId': 1, 'name': '耀莱成龙影城（温泉镇店）', 'addr': '海淀区温泉镇北部文化中心D座', 'lat': 40.04253, 'lng': 116.18892, 'poiId': 116256540, 'shopId': 69509274}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,173 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 27624, 'cityId': 1, 'name': '沙河镇中影智信影城', 'addr': '昌平区奇点中心（北京市能源东路1号）', 'lat': 40.15499, 'lng': 116.24909, 'poiId': 1682285192, 'shopId': 1682285192}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,174 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 36294, 'cityId': 1, 'name': '速铂影城北京路劲IMAX店', 'addr': '昌平区南邵镇路劲世界城三层速铂影城北京路劲IMAX店', 'lat': 40.207108, 'lng': 116.2923, 'poiId': 1787387368, 'shopId': 1787387368}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,175 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 66, 'cityId': 1, 'name': '大地影院（昌平菓岭假日店）', 'addr': '昌平区昌崔路203号果岭假日广场四楼', 'lat': 40.222176, 'lng': 116.264755, 'poiId': 1432377, 'shopId': 4510749}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,176 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 8186, 'cityId': 1, 'name': '首都电影院（昌平店 LUXE）', 'addr': '昌平区南环路10号院1号楼悦荟万科广场8层', 'lat': 40.2124, 'lng': 116.24025, 'poiId': 373237, 'shopId': 4620828}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,177 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 27629, 'cityId': 1, 'name': '新影联米瑞酷影城（昌平西关店）', 'addr': '昌平区西关路20号琥珀郡1号楼101室2层', 'lat': 40.223656, 'lng': 116.22086, 'poiId': 1981587730, 'shopId': 1981587730}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,178 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 36295, 'cityId': 1, 'name': '万达影城（乐多港万达广场店）', 'addr': '昌平区城南街道南口路29号3F-A乐多港万达广场3层万达影城', 'lat': 40.22989, 'lng': 116.19078, 'poiId': 693938016, 'shopId': 693938016}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,179 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 28446, 'cityId': 1, 'name': '龙泉国际影城（南口星城商场店）', 'addr': '昌平区南口镇南豆腐巷85号新世纪商城三层309', 'lat': 40.234882, 'lng': 116.13303, 'poiId': 1193668640, 'shopId': 1193668640}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,180 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 13, 'cityId': 1, 'name': '大地影院（延庆金锣湾店）', 'addr': '延庆区妫水北街39号1幢H座首楼金锣湾商业中心沃尔玛旁（金锣湾商业中心）', 'lat': 40.461914, 'lng': 115.97629, 'poiId': 1366944, 'shopId': 5476911}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,181 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 36047, 'cityId': 1, 'name': '万达影城（北京延庆店）', 'addr': '延庆区庆园街59号万达广场4层万达影城', 'lat': 40.47284, 'lng': 115.97979, 'poiId': 839123925, 'shopId': 839123925}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,182 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 14054, 'cityId': 1, 'name': '玫瑰之约汽车影院（半壁店）', 'addr': '大兴区东大路多维创新园内', 'lat': 39.62934, 'lng': 116.38452, 'poiId': 51400779, 'shopId': 23721770}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,183 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 36729, 'cityId': 1, 'name': '环球城市大道电影院', 'addr': '通州区环球大道1号院北京环球城市大道RE-02', 'lat': 39.85143, 'lng': 116.67482, 'poiId': 1769439210, 'shopId': 1769439210}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,184 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 15294, 'cityId': 1, 'name': '中传国际影城（亦庄店）', 'addr': '大兴区科创五街38号城乡世纪广场C座3层F3-C3006', 'lat': 39.802406, 'lng': 116.53342, 'poiId': 93839693, 'shopId': 58560670}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,185 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 11, 'cityId': 1, 'name': '新华国际影城（大兴店）', 'addr': '大兴区黄村东大街火神庙国际商业中心E座5层', 'lat': 39.72971, 'lng': 116.34166, 'poiId': 86394, 'shopId': 4293197}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,186 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 26229, 'cityId': 1, 'name': '完美云太狼影城（管庄店）', 'addr': '朝阳区管庄美廉美超市（云影小镇）一层', 'lat': 39.91095, 'lng': 116.59294, 'poiId': 189785406, 'shopId': 127043205}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,188 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 63, 'cityId': 1, 'name': '正华影城', 'addr': '丰台区宋家庄顺八条4号政馨园三区5号楼底商正华商城地下一层（宋家庄地铁B出口）', 'lat': 39.845528, 'lng': 116.43179, 'poiId': 82600, 'shopId': 4013677}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,189 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 9, 'cityId': 1, 'name': '星美国际影商城（分钟寺店）', 'addr': '丰台区南三环东路成寿寺路2号新业广场2楼', 'lat': 39.857136, 'lng': 116.44611, 'poiId': 1436294, 'shopId': 4283225}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,190 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 6057, 'cityId': 1, 'name': '星美国际影商城（西红门店）', 'addr': '大兴区西红门镇京良路10号乐家购物中心B区3层', 'lat': 39.799786, 'lng': 116.3325, 'poiId': 2490890, 'shopId': 9234215}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,191 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 27622, 'cityId': 1, 'name': '泰禾影城（马家堡4DX店）', 'addr': '丰台区角门19号新荟城购物中心4层泰禾影城马家堡店', 'lat': 39.836246, 'lng': 116.37812, 'poiId': 195082547, 'shopId': 132099086}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,192 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 28431, 'cityId': 1, 'name': '光华路5号艺术中心', 'addr': '朝阳区北京光华路5号院3号楼3层-4层', 'lat': 39.91395, 'lng': 116.45678, 'poiId': 1953355166, 'shopId': 1953355166}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,193 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 16458, 'cityId': 1, 'name': '北京东融国际影城（草桥免费停车店）', 'addr': '丰台区草桥东路1号上品折扣3层', 'lat': 39.850945, 'lng': 116.35827, 'poiId': 113165716, 'shopId': 72459955}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,194 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 98, 'cityId': 1, 'name': '星美国际影商城（世界城店）', 'addr': '朝阳区金汇路8号世界城E座B1楼（世贸天阶商业街北侧）', 'lat': 39.917755, 'lng': 116.45232, 'poiId': 316112, 'shopId': 3491605}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,195 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 14472, 'cityId': 1, 'name': '北京站电影院', 'addr': '东城区毛家湾胡同甲13号站西侧3层', 'lat': 39.90395, 'lng': 116.4272, 'poiId': 52795616, 'shopId': 23517911}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,196 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 15859, 'cityId': 1, 'name': 'DMG国际影城（悦秀店）', 'addr': '丰台区开阳路8号悦秀城6层', 'lat': 39.868313, 'lng': 116.37598, 'poiId': 94444126, 'shopId': 66240192}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,197 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 237, 'cityId': 1, 'name': '工人俱乐部电影院', 'addr': '西城区虎坊路口南7号', 'lat': 39.88806, 'lng': 116.38378, 'poiId': 1436438, 'shopId': 2412817}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,198 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 10781, 'cityId': 1, 'name': '耀莱成龙影城（王府井店）', 'addr': '东城区王府井大街301号新燕莎金街购物广场地下1层MB124', 'lat': 39.909725, 'lng': 116.41075, 'poiId': 6074394, 'shopId': 18693187}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,199 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 4541, 'cityId': 1, 'name': '东城图书馆影剧院', 'addr': '东城区交道口东大街85号区图书馆1楼', 'lat': 39.941, 'lng': 116.413, 'poiId': 271413, 'shopId': 1767631}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,200 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 4542, 'cityId': 1, 'name': '青少年剧场', 'addr': '丰台区西四环南路86号', 'lat': 39.851784, 'lng': 116.28421, 'poiId': 271414, 'shopId': 58318674}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,201 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 14387, 'cityId': 1, 'name': '剧空间剧场', 'addr': '西城区新街口北大街74号（近北京科学教育电影制片厂院内）', 'lat': 39.94392, 'lng': 116.37306, 'poiId': 73944402, 'shopId': 56768498}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,202 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 32398, 'cityId': 1, 'name': '未来影院', 'addr': '海淀区玉渊潭南路11号', 'lat': 39.91254, 'lng': 116.31886, 'poiId': 1687744041, 'shopId': 1687744041}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,203 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 180, 'cityId': 1, 'name': '顺义影剧院', 'addr': '顺义区新顺北大街3号（近便民街）', 'lat': 40.1338, 'lng': 116.650375, 'poiId': 89018, 'shopId': 1767742}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,203 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 25139, 'cityId': 1, 'name': '比高电影城（来广营）', 'addr': '朝阳区香宾路66号百安居2层', 'lat': 40.0166, 'lng': 116.465744, 'poiId': 165807827, 'shopId': 98843791}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,205 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 2010, 'cityId': 1, 'name': '中国电影资料馆', 'addr': '海淀区文慧园路3号（北京师范大学、枫蓝国际、积水潭桥、第二炮兵总医院）', 'lat': 39.953133, 'lng': 116.36986, 'poiId': 1541424, 'shopId': 2341354}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,205 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 7985, 'cityId': 1, 'name': '华影国际影城（花园路店）', 'addr': '海淀区花园路甲13号庚坊国际发展中心B1层', 'lat': 39.972046, 'lng': 116.36422, 'poiId': 4744457, 'shopId': 15089058}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,206 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 87, 'cityId': 1, 'name': '耀莱成龙影城（五棵松店）', 'addr': '海淀区复兴路69号蓝色港湾购物中心北区5层', 'lat': 39.913418, 'lng': 116.2794, 'poiId': 335220, 'shopId': 3716794}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,207 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 1589, 'cityId': 1, 'name': '新华国际影城（大钟寺店）', 'addr': '海淀区北三环西路甲18号大钟寺中坤广场西区3层', 'lat': 39.96575, 'lng': 116.34118, 'poiId': 1524564, 'shopId': 3928675}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,208 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 16496, 'cityId': 1, 'name': '华彩恐龙主题影城', 'addr': '顺义区后沙峪九重汇8层', 'lat': 40.10537, 'lng': 116.54243, 'poiId': 116704263, 'shopId': 70163944}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,209 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 23967, 'cityId': 1, 'name': '泰禾影城（立水桥店）', 'addr': '朝阳区安立路3号1幢1层106', 'lat': 40.04404, 'lng': 116.41106, 'poiId': 160457446, 'shopId': 93668974}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,210 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 1732, 'cityId': 1, 'name': '鲁信影城（立水桥店）', 'addr': '朝阳区立清路明天第一城7号院，蓝黛时空汇内', 'lat': 40.04711, 'lng': 116.4083, 'poiId': 1541423, 'shopId': 5605955}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,211 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 197, 'cityId': 1, 'name': '美嘉欢乐影城（中关村店）', 'addr': '海淀区中关村大街5号中关村广场购物中心3层（爱奇艺创新大厦南侧）', 'lat': 39.983105, 'lng': 116.313545, 'poiId': 279439, 'shopId': 2202985}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,212 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 60, 'cityId': 1, 'name': '燕山影剧院', 'addr': '房山区燕山岗南路3号（近燕山石化公司）', 'lat': 39.726925, 'lng': 115.96232, 'poiId': 271449, 'shopId': 1767784}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,213 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 15272, 'cityId': 1, 'name': '北京燕山文化活动中心影院', 'addr': '房山区迎风街道岗南路9号', 'lat': 39.7269, 'lng': 115.96208, 'poiId': 99082156, 'shopId': 58554256}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,214 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 183, 'cityId': 1, 'name': '密云大剧院', 'addr': '密云区鼓楼西大街1号', 'lat': 40.377117, 'lng': 116.84508, 'poiId': 1436412, 'shopId': 1767703}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,215 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 24069, 'cityId': 1, 'name': '米珈尼有渔影城', 'addr': '怀柔区南大街3号1幢101', 'lat': 40.31295, 'lng': 116.63654, 'poiId': 162782170, 'shopId': 95984113}]
(Background on this error at: http://sqlalche.me/e/f405)
2021-03-01 04:07:44,216 [DB.py:52] ERROR  db save Exception:(pymysql.err.ProgrammingError) (1146, "Table 'ticket.cinema' doesn't exist")
[SQL: INSERT INTO cinema (cinema_id, `cityId`, name, addr, lat, lng, `poiId`, `shopId`) VALUES (%(cinema_id)s, %(cityId)s, %(name)s, %(addr)s, %(lat)s, %(lng)s, %(poiId)s, %(shopId)s)]
[parameters: {'cinema_id': 15748, 'cityId': 1, 'name': '米珈尼汽车影院', 'addr': '怀柔区雁水路3号（雁栖湖景区正门停车场内）', 'lat': 40.397713, 'lng': 116.68635, 'poiId': 94728699, 'shopId': 65810261}]
(Background on this error at: http://sqlalche.me/e/f405)
